### ISSUE TITLE
 java.sql.SQLException: TDengine Error: invalid resultset pointer

### ISSUE THREAD

**Issue by Chaexsy** [taosdata/TDengine#2533] opened 2020-07-02 09:50 UTC
**Bug Description**
查询数据量较大时（13列数据，数据条数 > 1020条）抛 java.sql.SQLException: TDengine Error: invalid resultset pointer! 异常。
无论是使用原生JDBC还是Druid连接池都会出现这个问题。

修改 
按照论坛方案，修改服务端配置 shellActivityTimer 为20后，还是不能解决，打印的错误日志如下：
![image](https://user-images.githubusercontent.com/9604684/86424630-a3e6db80-bd15-11ea-87aa-65fbcac8ef50.png)

按照论坛另一个方案，修改服务的和客户端得连接为TCP后，JVM报错，截图如下：
![image](https://user-images.githubusercontent.com/9604684/86424685-c8db4e80-bd15-11ea-96d7-517d170c0af5.png)

目前找不到其他解决方案。

**Expected Behavior**
解决此问题的方案。

**Environment (please complete the following information):**
 - OS: Server：CentOS7.2，Client：win10 home。
 - Memory 16G, CPU-4, current Disk Space
 - TDengine Version [1.6.6.0-Linux-x64]
 - JDK1.8

**Comment by Aries-Lee1991** [comment] 2020-07-03 06:53
OK, we'll check it.

**Comment by xiaopingcs** [comment] 2020-07-15 07:54
Hi, @Chaexsy can you share your code and table schema, we will try to reproduce it.

**Comment by Chaexsy** [comment] 2020-07-16 01:28
Hi：
     Thank you for your willingness to solve my problem。
     My code has been typed into. Zip package，which is attached。




My main test class is TestTao.java,
and my create table function is  as follows picture:


and my insert data function is as follows picture:


and my query function is as follow picture:
















At 2020-07-15 15:54:49, "Xiao Ping" <notifications@github.com> wrote:

Hi, @Chaexsy can you share your code and table schema, we will try to reproduce it.

**Comment by xiaopingcs** [comment] 2020-07-16 06:29
cannot see your code or pictures, can you double check? or send to my email: xiaopingcs@outlook.com

**Comment by Chaexsy** [comment] 2020-07-16 07:22
I have sent a email to xiaopingcs@outlook.com, please check it.
















At 2020-07-16 14:29:53, "Xiao Ping" <notifications@github.com> wrote:

cannot see your code or pictures, can you double check? or send to my email: xiaopingcs@outlook.com

**Comment by xiaopingcs** [comment] 2020-07-18 06:22
Not able to reproduce your problem, please make sure your taosd is started. And use stmt.executeUpdate("use testdb") before your query. I am closing this issue, if you have other questions, please open a new one. 
<img width="1453" alt="Screen Shot 2020-07-18 at 2 16 13 PM" src="https://user-images.githubusercontent.com/65699335/87846371-f9b8a780-c901-11ea-91cb-a5cba871c3ca.png">
<img width="1025" alt="Screen Shot 2020-07-18 at 2 17 04 PM" src="https://user-images.githubusercontent.com/65699335/87846372-fa513e00-c901-11ea-9156-dcc8ea95f2a9.png">

**Closed by xiaopingcs** 2020-07-18 06:22 UTC
Labels: bug

**Comment by zyyang-taosdata** [comment] 2021-03-22 02:44
update your tdengine and jdbc-taosdriver to the lastest version to fix this issue
