### ISSUE TITLE
So many ERROR printed when run taosd 

### ISSUE THREAD

**Issue by tonycheng518** [taosdata/TDengine#2549] opened 2020-07-03 06:30 UTC
Hi, guys at taosdata, when I run taosd, it prints so many errors like this every 30s:
07/03 12:58:11.251401 28254 7ff2310bd700 ERROR MON monitor:0x7ff220000b20, save system info failed, code:-29 insert into log.dn_192_168_20_16 values(1593752273200773, 0.476112, 1.001478, 2, 32.617188, 3814.062500, 4929, 3.895123, 39, 7.941280, 3.001953, 2.495117, 0, 0, 0)
。。。
What these info mean? Is this ok? or something wrong seriously, thanks!
taos ver: 1.6.6.0
install type: from tar source file
os: ubuntu 18.04

**Comment by Aries-Lee1991** [comment] 2020-07-03 07:23
OK, we'll check it.

**Comment by xiaopingcs** [comment] 2020-07-03 07:41
@tonycheng518 when you start taosd 1.6.6.0, it will get your system info like info for cpu, memory, and write those info into log database. The error means taosd failed write those info.
Can you try start taos from your terminal and see if you can connect to taosd?

**Comment by tonycheng518** [comment] 2020-07-03 07:54
@xiaopingcs yes, taos can connect to taosd even though it is still printing annoying info

**Comment by xiaopingcs** [comment] 2020-07-03 08:03
Hi @tonycheng518, thanks for confirming. This could be a bug for us, but we don't have resource to look into it for now since we are all working on releasing our 2.0 version. You can use "systemctl start taosd" command to avoid the annoying info, or you can try our latest version, please feel free to report any issues.

**Comment by tonycheng518** [comment] 2020-07-03 08:15
ok, if it does not affect use, i will ignoring these annoying info. thanks!

**Comment by Aries-Lee1991** [comment] 2020-07-03 08:59
It seems the issue is already solved. I closed it.

**Closed by Aries-Lee1991** 2020-07-03 08:59 UTC
