### ISSUE TITLE
Can I dynamically adjust the retention time of database data files？

### ISSUE THREAD

**Issue by crazy11586** [taosdata/TDengine#2503] opened 2020-06-30 02:59 UTC
-- create database sql
"create database %s precision \"us\" keep 30;", tdengine_db_name

-- problems
I want to adjust the retention time of database data files to keep 20;

Can you Give me some advice? please

**Comment by liuyq-617** [comment] 2020-06-30 07:58
For some data security reasons, we prohibit dynamic modification of this parameter.

**Comment by crazy11586** [comment] 2020-06-30 08:25
> For some data security reasons, we prohibit dynamic modification of this parameter.

How should I modify it？

**Comment by crazy11586** [comment] 2020-06-30 08:27
> For some data security reasons, we prohibit dynamic modification of this parameter.

can't modify it after the database is specified ?

**Comment by liuyq-617** [comment] 2020-06-30 08:40
yes

**Comment by Aries-Lee1991** [comment] 2020-07-03 07:57
It seems the issue is already solved. I closed it.

**Closed by Aries-Lee1991** 2020-07-03 07:57 UTC
Labels: help wanted, question
