### ISSUE TITLE
查询全部表的最新一行数据，taosd.exe 异常

### ISSUE THREAD

**Issue by JunDon** [taosdata/TDengine#19478] opened 2023-01-10 07:37 UTC
taosd信息：
community version: 3.0.1.6 compatible_version: 3.0.0.0
gitinfo: 8b1f230d131f0023f8a055c2edb575bb57da6031
buildInfo: Built at 2022-11-04 16:35:44

数据库文件：
[https://www.wolai.com/tangjun/mJ8rBmuUXwBqMozoSqs1XZ](url)

1、查询单行数据  正常
select last_row(*) from  select last_row(*) from  idatasource202301091328191512410_ifegroup202301091328191564754_idata202301091329011871482
2、查询全部表最新数据服务器异常
 select last_row(*) from x group by tbname

**Comment by JunDon** [comment] 2023-01-10 07:39
数据库文件地址：
https://www.wolai.com/tangjun/mJ8rBmuUXwBqMozoSqs1XZ

**Comment by JunDon** [comment] 2023-01-10 09:25
update  3.0.22  to  fix

**Comment by gccgdb1234** [comment] 2023-01-30 09:08
Please upgrade to 3.0.2.4 to try again. If the issue is resolved, please kindly close this issue with a comment.

**Closed** 2024-05-22 06:10 UTC
Labels: bug
