### ISSUE TITLE
java ws数据订阅功能poll超时

### ISSUE THREAD

**Issue by yuyanmengxuan** [taosdata/TDengine#24035] opened 2023-12-12 08:44 UTC
1     Properties properties = new Properties();
            properties.setProperty("td.connect.ip","172.16.8.166");
            properties.setProperty("td.connect.port","6041");
            properties.setProperty(TMQConstants.BOOTSTRAP_SERVERS, "172.16.8.166:6041");
            properties.setProperty(TMQConstants.CONNECT_TYPE, "ws");
            properties.setProperty(TMQConstants.CONNECT_USER, "root");
            properties.setProperty(TMQConstants.CONNECT_PASS, "taosdata");
            properties.setProperty(TMQConstants.AUTO_OFFSET_RESET, "latest");
            properties.setProperty(TMQConstants.MSG_WITH_TABLE_NAME, "true");
            properties.setProperty(TMQConstants.ENABLE_AUTO_COMMIT, "true");
            properties.setProperty(TMQConstants.AUTO_COMMIT_INTERVAL, "1000");
            properties.setProperty(TMQConstants.GROUP_ID, "device_topic");
            properties.setProperty(TMQConstants.CLIENT_ID, "1");
            properties.setProperty(TMQConstants.VALUE_DESERIALIZER,
                    "td.config.MeterDeserializer");
            //properties.setProperty(TMQConstants.CONNECT_DB,"huitone");
            properties.setProperty(TMQConstants.VALUE_DESERIALIZER_ENCODING, "UTF-8");

            // poll data
            try (TaosConsumer<Meters> consumer = new TaosConsumer<>(properties)) {
                consumer.subscribe(Collections.singletonList(TOPIC));
                while (true) {
                    ConsumerRecords<Meters> meters = consumer.poll(Duration.ofMillis(50000));
                    for (ConsumerRecord<Meters> r : meters) {
                        System.out.println(JSON.toJSONString(r.value()));
                    }
                }
                //consumer.unsubscribe();
            }

        }。 ---- server版本3.2.1.0.   pom依赖    <taos.version>3.2.7</taos.version>

--错误描述
java.sql.SQLException: ERROR (0x2318): java.util.concurrent.TimeoutException: ERROR (0x231e): failed to complete the task:{"action":"subscribe","args":{"auto_commit":"true","auto_commit_interval_ms":"1000","client_id":"1","group_id":"test2","offset_rest":"earliest","password":"taosdata","req_id":1,"topics":["device_test"],"user":"root","with_table_name":"true"}} within the specified time : 60000,MILLISECONDS

日志：
<img width="1409" alt="image" src="https://github.com/taosdata/TDengine/assets/19608659/a28402b7-39f2-4269-96f1-dee782ff469e">

**Comment by yuyanmengxuan** [comment] 2023-12-12 08:59
earliest 这个参数也试过，好像都一样

**Comment by yu285** [comment] 2023-12-12 09:20
it has been fixed in 3.2.1.1

**Closed by yu285** 2023-12-12 09:20 UTC
Labels: bug

**Comment by hashmapybx** [comment] 2025-03-19 13:33
> it has been fixed in 3.2.1.1

你好，我在3.3.5.8版本中，flink cdc 测试报错：
Caused by: java.io.IOException: ERROR (0x231e): java.util.concurrent.TimeoutException: ERROR (0x231e): failed to complete the task:{"action":"subscribe","args":{"user":"root","password":"taosdata","db":null,"topics":["topic_meters"],"tz":null,"app":"java","ip":"","req_id":1,"group_id":"group_20","client_id":"clientId_0","offset_rest":"earliest","auto_commit":"false","auto_commit_interval_ms":null,"with_table_name":null}} within the specified time : 60000,MILLISECONDS
	at com.taosdata.flink.cdc.split.TDengineCdcSplitReader.fetch(TDengineCdcSplitReader.java:94)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:58)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:165)
